name: covid_19_tracker_in_flutter
description: Anl覺k olarak Covid-19 say覺lar覺n覺 takip edebilirsiniz.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0-dev.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: ^0.4.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.0+4
  lottie: ^0.3.3
  loading_indicator: ^1.1.0
  flutter_typeahead: ^1.8.0
  pull_to_refresh: ^1.5.8
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  shared_preferences: ^0.5.6+3
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: "^0.7.3"
  build_runner: ^1.8.1
  build_web_compilers: ^2.10.0

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/app_logo.png"

flutter_native_splash:
  image: assets/logo.png
  color: "F8F7F2"
  android_disable_fullscreen: true
  fill: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/    
    - assets/animations/